In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import warnings
warnings.filterwarnings('ignore')
digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)


In [3]:
lr=LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9574074074074074

In [4]:
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9851851851851852

In [5]:
rf=RandomForestClassifier(n_estimators=40)  
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9648148148148148

In [6]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [7]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [8]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [9]:

#logistic regression
lr=get_score(LogisticRegression(),X_train,X_test,y_train,y_test)

#svm
svc =get_score(SVC(),X_train,X_test,y_train,y_test)

#random forest
kf=get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test)

print('score for logistic regression',lr,'score for svm',svc,'score for random forest',kf)

score for logistic regression 0.9574074074074074 score for svm 0.9851851851851852 score for random forest 0.9722222222222222


In [25]:
# Initialize KFold with 5 splits
kf = KFold(n_splits=3)

# Lists to store the scores
scores_l = []
scores_svm = []
scores_rf = []

# Loop through the KFold splits
for train_index, test_index in kf.split(digits.data):
    X_train, X_test = digits.data[train_index], digits.data[test_index]
    y_train, y_test = digits.target[train_index], digits.target[test_index]
    
    # Get the scores for each model
    scores_l.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=150), X_train, X_test, y_train, y_test))

# Print the scores
print('Scores for Logistic Regression:', scores_l)
print('Scores for SVM:', scores_svm)
print('Scores for Random Forest:', scores_rf)

Scores for Logistic Regression: [0.9232053422370617, 0.9415692821368948, 0.9148580968280468]
Scores for SVM: [0.9666110183639399, 0.9816360601001669, 0.9549248747913188]
Scores for Random Forest: [0.9415692821368948, 0.9549248747913188, 0.9215358931552587]


In [28]:
from sklearn.model_selection import cross_val_score

#cross_val_score logistic regression
cross_val_score_lr= cross_val_score(LogisticRegression(),digits.data,digits.target,cv=3)
#cross_val_score svm
cross_val_score_svc=cross_val_score(SVC(),digits.data,digits.target,cv=3)
#cross_val_score random forest
cross_val_score_rf=cross_val_score(RandomForestClassifier(),digits.data,digits.target,cv=3)

# Print the cross validation scores
print('cross validation score for logistic regression',cross_val_score_lr,'cross validation score for svm',cross_val_score_svc,'cross validation score for random forest',cross_val_score_rf)

cross validation score for logistic regression [0.92153589 0.94156928 0.91652755] cross validation score for svm [0.96494157 0.97996661 0.96494157] cross validation score for random forest [0.93823038 0.95492487 0.92821369]
